version: '3.8'
services:
    frontend:
        build: ./frontend
        volumes:
            - ./frontend:/app
            - /app/node_modules
        ports:
            - '80:4200'

    eventbase:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=shimmie
            - POSTGRES_PASSWORD=shimmie
            - POSTGRES_DB=shimdb
        ports:
            - '5432:5432'

    backend:
        build: ./backend
        volumes:
            - ./backend:/app
            - /app/node_modules
        ports:
            - '8080:8080'
        environment:
            - PORT=8080
            - DATABASE_URL=postgresql://shimmie:shimmie@eventbase/shimdb
            - NODE_TLS_REJECT_UNAUTHORIZED=0
            - NODE_ENV=development
