version: '3.8'
services:
    eventbase:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=shimmie
            - POSTGRES_PASSWORD=shimmie
            - POSTGRES_DB=shimdb

    songserver:
        build: .
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - '8085:8085'
        environment:
            - SONG_PORT=8085
            - DATABASE_URL=postgresql://shimmie:shimmie@eventbase/shimdb
            - NODE_TLS_REJECT_UNAUTHORIZED=0
            - NODE_ENV=development
